In [ ]:
# check numpy version
import numpy as np
#np.__version__

'2.3.0'

In [5]:


ar1 = np.arange(1,20)
ar1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [7]:
ar2 = np.ones(7)
ar2

array([1., 1., 1., 1., 1., 1., 1.])

In [9]:
arr4 = np.zeros((2,3))
arr4

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
arr5 = np.linspace(1,10,50)
arr5

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [12]:
arr6 = np.arange(1,31).reshape(5,6)
arr6

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [15]:
arr7 = np.random.random(10)
#arr7 = np.random.randint(1,100,10)
arr7

array([0.44324447, 0.36622812, 0.24343926, 0.92332013, 0.68105593,
       0.75261529, 0.87461025, 0.46177865, 0.22846318, 0.43865957])

In [24]:
arr8 = np.arange(60).reshape((12,5))
print(arr8.shape)
#arr8.shape
#arr8.dtype
#arr8.size
#arr8.ndim
arr9=arr8.T.shape
arr9


(12, 5)


(5, 12)

In [27]:
arr10 = np.arange(1,10)[1:5]
print(arr10)



[2 3 4 5]


In [32]:
arr8[9:10,4:5][0][0]

np.int64(49)

In [22]:
arr8.ravel()
arr8.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [41]:
arr11 = np.arange(225).reshape(3,15,5)
arr11

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74]],

       [[ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99],
        [100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124],
        [125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134],
        [135, 136, 137, 138, 139],
        [140, 141,

In [42]:
arr11 = np.arange(1,61).reshape(15,4)
arr11

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32],
       [33, 34, 35, 36],
       [37, 38, 39, 40],
       [41, 42, 43, 44],
       [45, 46, 47, 48],
       [49, 50, 51, 52],
       [53, 54, 55, 56],
       [57, 58, 59, 60]])

In [48]:
arr11[0:,1:4,2:4]

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [49]:
np.max(arr8)
np.min(arr8)
np.sum(arr8)
np.mean(arr8)
np.median(arr8)
np.std(arr8)

np.float64(125.40628528462554)

In [50]:
arr8.sort()

In [53]:
arr11 = np.array([1,2,3,4,5])
arr11.argsort()

array([0, 1, 2, 3, 4])

In [54]:
ar2 = np.array([1,2,3,4,5],ndmin=6)
ar2

array([[[[[[1, 2, 3, 4, 5]]]]]])